# Generated by Django 4.1.5 on 2023-02-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickers',
            new_name='Ticker',
        ),
    ]
