# Generated by Django 4.1.5 on 2023-02-27 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_rename_tickers_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksprice',
            name='information',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
