# Generated by Django 4.1.5 on 2023-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StocksPricePredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('last_refreshed', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=20)),
                ('data_size', models.IntegerField()),
                ('predicted_data', models.JSONField()),
                ('best_model', models.CharField(max_length=20)),
                ('models_accuracy', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
